# -*- coding: utf-8 -*-
"""crawl4ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11qv4nIqLYKkVelzBcWpWdAyWWd5N3G4u
"""

!pip install "crawl4ai @ git+https://github.com/unclecode/crawl4ai.git"

from crawl4ai import WebCrawler

crawler = WebCrawler()

crawler.warmup()

result = crawler.run(
    url = "https://zbiz.io/"
)

# Print the extracted content
print(result.markdown)